name: Test on Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.11
          environment-file: environment.yml
          activate-environment: test-env
      - name: Install Dependencies
        run: conda install -c conda-forge chromadb --yes
      - name: Run test
        run: |
          echo "Running tests"
          python test_import.py
